//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { usersEntity } from './db/users.entity';
import { departmentsEntity } from './db/departments.entity';
import { initiativesEntity } from './db/initiatives.entity';
import { goalsEntity } from './db/goals.entity';
import { emissionSourcesEntity } from './db/emissionSources.entity';
import { resourceUsageEntity } from './db/resourceUsage.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      usersEntity,
      departmentsEntity,
      initiativesEntity,
      goalsEntity,
      emissionSourcesEntity,
      resourceUsageEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      users: [
        {
          userName: 'userName 1',
          department: 1,
          password: 'password 1',
          email: 'email 1',
          id: 52,
        },
        {
          userName: 'userName 2',
          department: 2,
          password: 'password 2',
          email: 'email 2',
          id: 34,
        },
        {
          userName: 'userName 3',
          department: 3,
          password: 'password 3',
          email: 'email 3',
          id: 18,
        },
        {
          userName: 'userName 4',
          department: 4,
          password: 'password 4',
          email: 'email 4',
          id: 29,
        },
        {
          userName: 'userName 5',
          department: 5,
          password: 'password 5',
          email: 'email 5',
          id: 60,
        },
      ],
      departments: [
        { departmentName: 'departmentName 1', departmentHead: 1, id: 51 },
        { departmentName: 'departmentName 2', departmentHead: 2, id: 71 },
        { departmentName: 'departmentName 3', departmentHead: 3, id: 73 },
        { departmentName: 'departmentName 4', departmentHead: 4, id: 78 },
        { departmentName: 'departmentName 5', departmentHead: 5, id: 53 },
      ],
      initiatives: [
        {
          name: 'name 1',
          description: 'description 1',
          startDate: '2025-02-15T20:58:01.577Z',
          endDate: '2024-09-23T12:16:53.052Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 96,
        },
        {
          name: 'name 2',
          description: 'description 2',
          startDate: '2024-01-21T15:22:18.355Z',
          endDate: '2025-02-24T03:54:32.660Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 78,
        },
        {
          name: 'name 3',
          description: 'description 3',
          startDate: '2023-11-30T09:19:04.645Z',
          endDate: '2024-03-03T16:23:46.745Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 40,
        },
        {
          name: 'name 4',
          description: 'description 4',
          startDate: '2024-11-15T23:51:54.994Z',
          endDate: '2025-04-01T19:03:55.137Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 70,
        },
        {
          name: 'name 5',
          description: 'description 5',
          startDate: '2024-06-26T06:07:25.874Z',
          endDate: '2023-08-04T08:39:33.877Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 89,
        },
      ],
      goals: [
        {
          name: 'name 1',
          description: 'description 1',
          targetDate: '2023-07-01T16:33:32.997Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 67,
        },
        {
          name: 'name 2',
          description: 'description 2',
          targetDate: '2023-06-04T14:47:11.263Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 23,
        },
        {
          name: 'name 3',
          description: 'description 3',
          targetDate: '2024-12-02T15:24:57.062Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 97,
        },
        {
          name: 'name 4',
          description: 'description 4',
          targetDate: '2023-04-29T21:03:48.060Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 15,
        },
        {
          name: 'name 5',
          description: 'description 5',
          targetDate: '2023-08-24T04:19:11.611Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 33,
        },
      ],
      emissionSources: [
        {
          sourceType: 'sourceType 1',
          quantityUsed: 0.77,
          emissionFactors: 0.61,
          totalEmissions: 0.53,
          id: 92,
        },
        {
          sourceType: 'sourceType 2',
          quantityUsed: 0.81,
          emissionFactors: 0.24,
          totalEmissions: 0.34,
          id: 7,
        },
        {
          sourceType: 'sourceType 3',
          quantityUsed: 0.99,
          emissionFactors: 0.52,
          totalEmissions: 0.15,
          id: 76,
        },
        {
          sourceType: 'sourceType 4',
          quantityUsed: 0.82,
          emissionFactors: 0.38,
          totalEmissions: 0.23,
          id: 6,
        },
        {
          sourceType: 'sourceType 5',
          quantityUsed: 0.77,
          emissionFactors: 0.49,
          totalEmissions: 0.1,
          id: 46,
        },
      ],
      resourceUsage: [
        {
          resourceType: 'resourceType 1',
          quantityConsumed: 0.78,
          unitOfMeasurement: 'unitOfMeasurement 1',
          periodOfConsumption: '2024-05-21T22:13:38.300Z',
          id: 18,
        },
        {
          resourceType: 'resourceType 2',
          quantityConsumed: 0.45,
          unitOfMeasurement: 'unitOfMeasurement 2',
          periodOfConsumption: '2023-04-29T07:11:35.259Z',
          id: 65,
        },
        {
          resourceType: 'resourceType 3',
          quantityConsumed: 0.34,
          unitOfMeasurement: 'unitOfMeasurement 3',
          periodOfConsumption: '2025-03-10T07:14:53.998Z',
          id: 30,
        },
        {
          resourceType: 'resourceType 4',
          quantityConsumed: 0.09,
          unitOfMeasurement: 'unitOfMeasurement 4',
          periodOfConsumption: '2024-05-09T06:01:58.036Z',
          id: 74,
        },
        {
          resourceType: 'resourceType 5',
          quantityConsumed: 0.5,
          unitOfMeasurement: 'unitOfMeasurement 5',
          periodOfConsumption: '2023-12-13T19:50:39.150Z',
          id: 18,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('usersEntity', data.users);
      await this.SeedResource('departmentsEntity', data.departments);
      await this.SeedResource('initiativesEntity', data.initiatives);
      await this.SeedResource('goalsEntity', data.goals);
      await this.SeedResource('emissionSourcesEntity', data.emissionSources);
      await this.SeedResource('resourceUsageEntity', data.resourceUsage);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
